#!/bin/bash

OUTDIR=`pwd`
JOBNAME=`basename $1 | sed 's/\.[^\.]*$//'`
LOGFILE=${OUTDIR}/${JOBNAME}_crest.log
WORKDIR=/tmp/crest_${JOBNAME}_$$
mkdir -p ${WORKDIR}

# Copy input files and reference file 
for ARG in "$@"
do
  if [ -f ${ARG} ]; then
    cp ${ARG} ${WORKDIR}
    dos2unix ${ARG} > /dev/null 2>&1
    REF_FILE=$(sed -n 's/^[[:space:]]*reference=//p' "$ARG")
    if [ -n "$REF_FILE" ] && [ -f "$REF_FILE" ]; then
      cp $REF_FILE $WORKDIR
    fi
  fi  
done

# Run
cd ${WORKDIR}
crest "$@" 2>&1 | tee ${LOGFILE}

# Copy results
cp -r * ${OUTDIR}

# Clean-up
cd ${OUTDIR}
rm -rf ${WORKDIR}

